title: Clean Paani
email: cleanpaanisite@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The #1 resource on water purifiers - RO, UV, UF water purifiers, the technology
  behind these water purifiers, and our reviews of the popular products in the market. 
author: Krishna
publisher: CleanPaani.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#disqus:
#  shortname: crypto512


twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - contact.md
 - privacy.md


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
